name: hdbo_benchmark 
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy<2
    - botorch
    - seaborn
    - CairoSVG
    - wandb
    - click
    - fair-esm
    - lightning
    - "git+https://github.com/MachineLearningLifeScience/poli.git@dev"
    - "git+https://github.com/MachineLearningLifeScience/poli-baselines.git@main"
    - -e .