[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "/docs/hdbo/introduction"
  weight = 20

[[main]]
  name = "Benchmarks"
  pageRef = "/benchmarks"
  weight = 30

[[main]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/MachineLearningLifeScience/hdbo_benchmark"
  weight = 60
  [main.params]
    icon = true

# [[social]]
#   name = "LinkedInaaa"
#   pre = "fab linkedin"
#   url = "https://linkedin.com/aaa.aaa"
#   weight = 10
# 
# [[social]]
#   name = "GitHubaa"
#   pre = "fab fa-github"
#   url = "https://github.com/"
#   weight = 20
# 
# [[social]]
#   name = "Medium"
#   pre = "fab medium"
#   url = "https://medium.com/"
#   weight = 30